<?php

declare(strict_types=1);

namespace Nowo\CookieConsentBundle\DependencyInjection;

use Nowo\CookieConsentBundle\Enum\CategoryEnum;
use Nowo\CookieConsentBundle\Enum\DisabledRoutesEnum;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

use function is_string;

/**
 * Defines the configuration tree for the cookie consent bundle.
 */
class Configuration implements ConfigurationInterface
{
    public const ALIAS = 'nowo_cookie_consent';

    public const CSS_FRAMEWORKS = ['bootstrap', 'bootstrap4', 'bootstrap5', 'tailwind', 'foundation', 'custom', 'tabler', 'none'];

    /**
     * Builds the configuration tree for bundle settings.
     *
     * @return TreeBuilder The root configuration tree builder
     */
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder(self::ALIAS);
        $rootNode    = $treeBuilder->getRootNode();

        $rootNode
            ->addDefaultsIfNotSet()
            ->children()
                ->arrayNode('doctrine')
                    ->info('Doctrine DBAL connection and table prefix for cookie consent entities.')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('connection')
                            ->info('Name of the Doctrine DBAL connection to use (e.g. default, or a custom connection).')
                            ->defaultValue('default')
                        ->end()
                        ->scalarNode('table_prefix')
                            ->info('Prefix prepended to table names (dashboard_cookie_log, dashboard_cookie_config, …). Empty = no prefix.')
                            ->defaultValue('')
                        ->end()
                    ->end()
                ->end()
                ->scalarNode('table_prefix')
                    ->defaultValue('')
                    ->setDeprecated('nowo-tech/cookie-consent-bundle', '1.3', 'Use doctrine.table_prefix instead.')
                    ->info('Deprecated. Use doctrine.table_prefix (e.g. "app_" yields app_dashboard_cookie_log).')
                    ->example('app_')
                ->end()
                ->arrayNode('categories')
                    ->scalarPrototype()->end()
                    ->defaultValue([
                        CategoryEnum::CATEGORY_ANALYTICS,
                        CategoryEnum::CATEGORY_MARKETING,
                        CategoryEnum::CATEGORY_PREFERENCES,
                    ])
                    ->info('Cookie categories shown in the consent modal (excluding "required").')
                ->end()
                ->booleanNode('use_logger')
                    ->defaultTrue()
                    ->info('Persist consent choices to the database when true.')
                ->end()
                ->booleanNode('use_database_config')
                    ->defaultFalse()
                    ->info('Load modal copy and display settings from CookieConsentConfig entities when true.')
                ->end()
                ->booleanNode('use_cookie_inventory')
                    ->defaultFalse()
                    ->info('Expose cookie definitions (name, category/block, duration, provider, purpose) in the preferences modal and legal pages.')
                ->end()
                ->arrayNode('cookie_inventory')
                    ->defaultValue([])
                    ->info('Static cookie definitions when not using Doctrine entities (ignored when the active profile has CookieDefinition rows).')
                    ->prototype('array')
                        ->children()
                            ->scalarNode('name')->isRequired()->cannotBeEmpty()->end()
                            ->scalarNode('duration')->defaultValue('')->end()
                            ->scalarNode('category')->defaultValue('required')->end()
                            ->scalarNode('type')->defaultValue('first_party')->end()
                            ->integerNode('sort_order')->defaultValue(0)->end()
                            ->scalarNode('provider')->defaultNull()->end()
                            ->scalarNode('purpose')->defaultNull()->end()
                            ->arrayNode('translations')
                                ->prototype('array')
                                    ->children()
                                        ->scalarNode('provider')->defaultValue('')->end()
                                        ->scalarNode('purpose')->defaultValue('')->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->booleanNode('fetch_config_via_api')
                    ->defaultFalse()
                    ->info('Expose GET /cookie-consent/config and let the frontend script load settings via fetch().')
                ->end()
                ->booleanNode('http_only')
                    ->defaultTrue()
                    ->info('Set HttpOnly flag on consent cookies.')
                ->end()
                ->scalarNode('form_action')
                    ->defaultNull()
                    ->info('Optional route name used as the form action URL.')
                ->end()
                ->booleanNode('csrf_protection')
                    ->defaultTrue()
                    ->info('Enable CSRF protection on the consent form.')
                ->end()
                ->arrayNode('disabled_routes')
                    ->scalarPrototype()->end()
                    ->defaultValue([
                        DisabledRoutesEnum::DISABLED_ROUTE_PRIVACY,
                        DisabledRoutesEnum::DISABLED_ROUTE_IMPRINT,
                    ])
                    ->info('Route names where the modal must not open automatically.')
                ->end()
                ->arrayNode('skip_render_routes')
                    ->scalarPrototype()->end()
                    ->defaultValue([])
                    ->info('Route name patterns (fnmatch wildcards allowed) where the consent fragment must not render at all (empty response; no inventory/config queries). Use for authenticated dashboards/admin shells.')
                ->end()
                ->enumNode('route_targeting_mode')
                    ->values(['all', 'only', 'except'])
                    ->defaultValue('all')
                    ->info('Controls where the modal auto-opens: all pages, only listed routes, or all except listed routes.')
                ->end()
                ->arrayNode('target_routes')
                    ->scalarPrototype()->end()
                    ->defaultValue([])
                    ->info('Route names used with route_targeting_mode (Symfony route names, one per line in the admin UI).')
                ->end()
                ->scalarNode('default_locale')
                    ->defaultValue('en')
                    ->info('Fallback locale when no supported language can be detected.')
                    ->example('en')
                ->end()
                ->arrayNode('enabled_locales')
                    ->scalarPrototype()->end()
                    ->defaultValue(['en', 'es', 'it', 'fr', 'de', 'pt', 'nl', 'pl', 'ca'])
                    ->info('Locales supported by the cookie consent UI and locale detection.')
                ->end()
                ->booleanNode('detect_locale_from_accept_language')
                    ->defaultTrue()
                    ->info('Use the Accept-Language request header when no explicit locale is available.')
                ->end()
                ->enumNode('ui_theme')
                    ->values(['bootstrap', 'tailwind'])
                    ->defaultValue('bootstrap')
                    ->info('UI framework used by the bundled cookie consent modal templates.')
                ->end()
                ->enumNode('color_theme')
                    ->values(['light', 'dark', 'dark-turquoise', 'light-funky', 'elegant-black'])
                    ->defaultValue('light')
                ->end()
                ->booleanNode('dark_mode_enabled')->defaultFalse()->end()
                ->booleanNode('disable_transitions')->defaultFalse()->end()
                ->booleanNode('disable_page_interaction')
                    ->defaultFalse()
                    ->info('When true, adds a full-page overlay and blocks scrolling until the user chooses an option.')
                ->end()
                ->booleanNode('two_step_modal')->defaultFalse()->end()
                ->booleanNode('open_preferences_modal')->defaultFalse()->end()
                ->booleanNode('manage_iframe_placeholders')->defaultFalse()->end()
                ->booleanNode('granular_cookie_selection')
                    ->defaultFalse()
                    ->info('When true, optional cookies can be toggled individually inside each category block.')
                ->end()
                ->booleanNode('preferences_bubble_enabled')
                    ->defaultFalse()
                    ->info('Shows a floating cookie icon button to reopen the preferences modal after consent is saved.')
                ->end()
                ->enumNode('preferences_bubble_position')
                    ->values(['bottom-right', 'bottom-left', 'top-right', 'top-left'])
                    ->defaultValue('bottom-right')
                    ->info('Screen corner for the floating preferences bubble.')
                ->end()
                ->scalarNode('preferences_bubble_border_color')
                    ->defaultNull()
                    ->info('Hex color for the preferences bubble border and cookie icon (e.g. #30363c).')
                ->end()
                ->scalarNode('preferences_bubble_icon')
                    ->defaultNull()
                    ->info('Custom HTML or SVG markup for the preferences bubble icon. Leave empty for the default cookie SVG.')
                ->end()
                ->arrayNode('preference_sections')
                    ->defaultValue([])
                    ->info('Optional preference modal sections (title, description, categories).')
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('title')->defaultValue('')->end()
                            ->scalarNode('description')->defaultValue('')->end()
                            ->arrayNode('categories')
                                ->scalarPrototype()->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('web_ui')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                            ->info('When false, admin access subscriber is not registered (routes still load; prefer security firewall).')
                        ->end()
                        ->scalarNode('path_prefix')
                            ->defaultValue('/cookie-consent-config')
                            ->cannotBeEmpty()
                            ->info('Documented URL path prefix for admin CRUD (host should lock with security.access_control).')
                            ->validate()
                                ->ifTrue(static fn ($v): bool => !is_string($v) || !str_starts_with($v, '/'))
                                ->thenInvalid('path_prefix must be a string starting with /')
                            ->end()
                        ->end()
                        ->scalarNode('layout_template')
                            ->defaultValue('@NowoCookieConsentBundle/admin/layout.html.twig')
                            ->cannotBeEmpty()
                            ->info('Twig layout extended by admin pages (global nowo_cookie_consent_layout_template). Set to your app layout or a one-file bridge.')
                        ->end()
                        ->enumNode('css_framework')
                            ->values(self::CSS_FRAMEWORKS)
                            ->defaultValue('bootstrap5')
                            ->info('Host CSS stack hint: bootstrap5 | bootstrap4 | bootstrap | tailwind | foundation | tabler | custom | none.')
                        ->end()
                        ->enumNode('icon_set')
                            ->values(['bootstrap-icons', 'tabler-icons', 'ux_icon', 'svg_inline', 'none'])
                            ->defaultValue('bootstrap-icons')
                        ->end()
                        ->integerNode('list_page_size')
                            ->defaultValue(20)
                            ->min(1)
                            ->max(200)
                            ->info('Default page size for admin cookie definition lists.')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('security')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('access_checker')
                            ->defaultNull()
                            ->info('Optional service id implementing CookieConsentAccessCheckerInterface.')
                        ->end()
                        ->arrayNode('access_roles')
                            ->scalarPrototype()->end()
                            ->defaultValue(['ROLE_ADMIN'])
                            ->info('Roles that may access admin CRUD. Empty disables bundle-level role checks.')
                        ->end()
                        ->booleanNode('allow_unauthenticated')
                            ->defaultFalse()
                            ->info('DEV/DEMO ONLY. When true, admin UI may load without SecurityBundle / without login. Production MUST keep false.')
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
