nowo_cookie_consent:
    table_prefix: 'demo_'
    use_logger: true
    use_database_config: true
    use_cookie_inventory: true
    fetch_config_via_api: true
    default_locale: en
    enabled_locales:
        - en
        - es
        - it
        - fr
        - de
        - pt
        - nl
        - pl
        - ca
    detect_locale_from_accept_language: false
    categories:
        - functionality
        - analytics
        - marketing
        - preferences
